services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=project2'
      - 'MARIADB_PASSWORD=kyg9i83u8gaw66om'
      - 'MARIADB_USER=xclf17f8q3gskjaf'
    ports:
      - '3306:3306'

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GOOGLE_CLIENT_ID=701122319569-02h8g47mlbebhc75bs34n1qipotmvpvc.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - DB_USERNAME=xclf17f8q3gskjaf
      - DB_PASSWORD=kyg9i83u8gaw66om
