#version: '3.8'

services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=j5rt3g818hv4m3ie'
      - 'MARIADB_PASSWORD=hkifyebgdfnairxk'
      - 'MARIADB_USER=xclf17f8q3gskjaf'
      - 'MARIADB_ROOT_PASSWORD=9J&1pLz!cR#12xQ'
    ports:
      - '3307:3306'  # Use port 3306 on the host
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 15

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GOOGLE_CLIENT_ID=701122319569-02h8g47mlbebhc75bs34n1qipotmvpvc.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - DB_USERNAME=xclf17f8q3gskjaf
      - DB_PASSWORD=hkifyebgdfnairxk
