services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=j5rt3g818hv4m3ie'
      - 'MARIADB_PASSWORD=kyg9i83u8gaw66om'
      - 'MARIADB_USER=xclf17f8q3gskjaf'
    ports:
      - '3306:3306'

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080